package ok.dht.test.siniachenko.exception;

public class ServiceInternalErrorException extends Exception {
    public ServiceInternalErrorException(Throwable cause) {
        super(cause);
    }
}
